image: node:20 

stages: 
  - install
  - test
  - save 

install_dep: 
  stage: install
  script: 
    - npm install
  cache: 
    paths: 
      - node_modules/

run_tests: 
  stage: test
  script: 
    - npm test
  cache: 
    paths: 
      - node_modules/  